from datetime import datetime
from io import BytesIO
import logging
from typing import Any
from html import escape
import base64
import re

from matplotlib.figure import Figure
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import Image as ReportImage, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


logger = logging.getLogger(__name__)



class NumberedFooterCanvas(Canvas):
    """Two-pass canvas for stable `Page X of Y` footers.

    ReportLab exposes the current page number during drawing, but not the final
    page count. This canvas stores each page state, then replays pages once the
    total is known. It deliberately draws only a restrained footer and never a
    decorative page frame.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self) -> None:  # noqa: N802 - ReportLab API
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        page_count = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_footer(page_count)
            super().showPage()
        super().save()

    def _draw_footer(self, page_count: int) -> None:
        page_width, _page_height = self._pagesize
        left_margin = 0.7 * inch
        right_margin = 0.7 * inch
        baseline = 0.43 * inch
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#4B5563"))
        self.drawString(left_margin, baseline, "Generated by DorjeAI | Lotus & Dorje")
        self.drawRightString(page_width - right_margin, baseline, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class DorjeReportExporter:
    def export_pdf(self, report_text: str, title: str = "DorjeAI Report", chart_assets: list | None = None) -> bytes:
        buffer = BytesIO()
        styles = self._pdf_styles()
        page_width, _page_height = letter
        margins = 0.7 * inch
        usable_width = page_width - (2 * margins)
        story: list[Any] = [
            Paragraph("Lotus & Dorje", styles["brand"]),
            Paragraph(self._inline_markup(title), styles["title"]),
            Paragraph(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["meta"]),
            Spacer(1, 0.18 * inch),
        ]

        math_cache: dict[str, bytes] = {}
        for block in self._parse_blocks(report_text):
            story.extend(self._block_to_flowables(block, styles, usable_width, math_cache))

        for asset in chart_assets or []:
            image_data_url = getattr(asset, "image_data_url", "")
            if not image_data_url.startswith("data:image/"):
                continue
            try:
                image_bytes = base64.b64decode(image_data_url.split(",", 1)[1])
                story.extend([PageBreak(), Paragraph(self._inline_markup(getattr(asset, "title", "Chart")), styles["h2"])])
                chart = ReportImage(BytesIO(image_bytes), width=min(usable_width, 6.7 * inch), height=4.02 * inch)
                chart.hAlign = "CENTER"; story.extend([chart, Spacer(1, 0.12 * inch)])
                dataset = getattr(asset, "dataset", None)
                if dataset and dataset.columns and dataset.rows:
                    story.extend([Paragraph("Source data", styles["h3"]), self._table_flowable([dataset.columns, *dataset.rows], styles, usable_width)])
            except (ValueError, IndexError, OSError) as exc:
                logger.warning("Unable to export chart in PDF", exc_info=exc)

        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=margins,
            leftMargin=margins,
            topMargin=0.72 * inch,
            bottomMargin=0.76 * inch,
        )
        doc.build(story, canvasmaker=NumberedFooterCanvas)
        buffer.seek(0)
        return buffer.getvalue()

    def _pdf_styles(self) -> dict[str, ParagraphStyle]:
        styles = getSampleStyleSheet()
        body = ParagraphStyle(
            "DorjeBodyReadable",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=10.5,
            leading=14,
            textColor=colors.HexColor("#1F2937"),
            alignment=TA_LEFT,
            spaceAfter=6,
            splitLongWords=True,
        )
        return {
            "brand": ParagraphStyle("DorjeBrand", parent=body, fontName="Helvetica-Bold", fontSize=10, leading=13, textColor=colors.HexColor("#059669"), alignment=TA_CENTER, spaceAfter=2),
            "title": ParagraphStyle("DorjeTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=18, leading=22, textColor=colors.HexColor("#111827"), alignment=TA_CENTER, spaceAfter=10),
            "meta": ParagraphStyle("DorjeMeta", parent=body, fontSize=9, leading=12, textColor=colors.HexColor("#6B7280"), alignment=TA_CENTER, spaceAfter=8),
            "h1": ParagraphStyle("DorjeH1", parent=body, fontName="Helvetica-Bold", fontSize=15, leading=19, textColor=colors.HexColor("#064E3B"), spaceBefore=12, spaceAfter=7),
            "h2": ParagraphStyle("DorjeH2", parent=body, fontName="Helvetica-Bold", fontSize=13, leading=17, textColor=colors.HexColor("#111827"), spaceBefore=10, spaceAfter=6),
            "h3": ParagraphStyle("DorjeH3", parent=body, fontName="Helvetica-Bold", fontSize=12, leading=15, textColor=colors.HexColor("#374151"), spaceBefore=8, spaceAfter=5),
            "h4": ParagraphStyle("DorjeH4", parent=body, fontName="Helvetica-Bold", fontSize=11, leading=14, textColor=colors.HexColor("#374151"), spaceBefore=6, spaceAfter=4),
            "body": body,
            "bullet": ParagraphStyle("DorjeBullet", parent=body, leftIndent=18, firstLineIndent=0, bulletIndent=7, spaceAfter=3),
            "number": ParagraphStyle("DorjeNumber", parent=body, leftIndent=20, firstLineIndent=0, bulletIndent=7, spaceAfter=3),
            "quote": ParagraphStyle("DorjeQuote", parent=body, leftIndent=18, rightIndent=12, borderColor=colors.HexColor("#D1D5DB"), borderWidth=0.7, borderPadding=6, backColor=colors.HexColor("#F9FAFB"), textColor=colors.HexColor("#374151"), spaceBefore=4, spaceAfter=7),
            "code": ParagraphStyle("DorjeCode", parent=body, fontName="Courier", fontSize=8.5, leading=11, backColor=colors.HexColor("#F3F4F6"), borderColor=colors.HexColor("#D1D5DB"), borderWidth=0.4, borderPadding=5, splitLongWords=True),
            "table_cell": ParagraphStyle("DorjeTableCell", parent=body, fontSize=8.5, leading=10.5, spaceAfter=0, splitLongWords=True),
            "table_head": ParagraphStyle("DorjeTableHead", parent=body, fontName="Helvetica-Bold", fontSize=8.5, leading=10.5, textColor=colors.white, spaceAfter=0, splitLongWords=True),
        }

    def _parse_blocks(self, text: str) -> list[dict[str, Any]]:
        blocks: list[dict[str, Any]] = []
        lines = text.splitlines()
        index = 0
        while index < len(lines):
            raw = lines[index]
            stripped = raw.strip()
            if not stripped:
                index += 1
                continue
            if stripped in {"---PAGE---", "<!-- pagebreak -->", "\\pagebreak"}:
                blocks.append({"type": "page_break"})
                index += 1
                continue
            if stripped.startswith("```"):
                code_lines: list[str] = []
                index += 1
                while index < len(lines) and not lines[index].strip().startswith("```"):
                    code_lines.append(lines[index])
                    index += 1
                blocks.append({"type": "code", "text": "\n".join(code_lines)})
                index += 1
                continue
            if stripped.startswith("$$"):
                formula_parts = [stripped.removeprefix("$$")]
                while not formula_parts[-1].rstrip().endswith("$$") and index + 1 < len(lines):
                    index += 1
                    formula_parts.append(lines[index].strip())
                formula = "\n".join(formula_parts).strip()
                formula = formula.removesuffix("$$").strip()
                blocks.append({"type": "math", "formula": formula})
                index += 1
                continue
            if stripped.startswith("|") and stripped.endswith("|"):
                table_lines: list[str] = []
                while index < len(lines):
                    candidate = lines[index].strip()
                    if not (candidate.startswith("|") and candidate.endswith("|")):
                        break
                    table_lines.append(candidate)
                    index += 1
                rows = self._parse_markdown_table(table_lines)
                if rows:
                    blocks.append({"type": "table", "rows": rows})
                continue
            heading = re.match(r"^(#{1,4})\s+(.+)$", stripped)
            if heading:
                blocks.append({"type": "heading", "level": len(heading.group(1)), "text": heading.group(2)})
            elif re.match(r"^[-*+]\s+", stripped):
                blocks.append({"type": "bullet", "text": re.sub(r"^[-*+]\s+", "", stripped)})
            elif match := re.match(r"^(\d+)[.)]\s+(.+)$", stripped):
                blocks.append({"type": "number", "number": match.group(1), "text": match.group(2)})
            elif stripped.startswith(">"):
                blocks.append({"type": "quote", "text": re.sub(r"^>\s?", "", stripped)})
            else:
                paragraph_lines = [stripped]
                while index + 1 < len(lines):
                    nxt = lines[index + 1].strip()
                    if not nxt or nxt.startswith(("```", "$$", "|", "#", ">", "- ", "* ", "+ ")) or re.match(r"^\d+[.)]\s+", nxt):
                        break
                    paragraph_lines.append(nxt)
                    index += 1
                blocks.append({"type": "paragraph", "text": " ".join(paragraph_lines)})
            index += 1
        return blocks

    def _parse_markdown_table(self, table_lines: list[str]) -> list[list[str]]:
        rows: list[list[str]] = []
        for table_line in table_lines:
            cells = [cell.strip() for cell in table_line[1:-1].split("|")]
            if not cells or all(not cell for cell in cells):
                continue
            if all(re.fullmatch(r":?-{3,}:?", cell.replace(" ", "")) for cell in cells):
                continue
            rows.append(cells)
        if not rows:
            return []
        width = max(len(row) for row in rows)
        return [(row + [""] * width)[:width] for row in rows]

    def _block_to_flowables(self, block: dict[str, Any], styles: dict[str, ParagraphStyle], usable_width: float, math_cache: dict[str, bytes]) -> list[Any]:
        block_type = block.get("type")
        if block_type == "page_break":
            return [PageBreak()]
        if block_type == "heading":
            level = min(max(int(block.get("level", 2)), 1), 4)
            return [Paragraph(self._inline_markup(str(block.get("text", ""))), styles[f"h{level}"])]
        if block_type == "bullet":
            return [Paragraph(self._inline_markup(str(block.get("text", ""))), styles["bullet"], bulletText="•")]
        if block_type == "number":
            return [Paragraph(self._inline_markup(str(block.get("text", ""))), styles["number"], bulletText=f"{block.get('number', '1')}.")]
        if block_type == "quote":
            return [Paragraph(self._inline_markup(str(block.get("text", ""))), styles["quote"])]
        if block_type == "code":
            return [Paragraph(escape(str(block.get("text", ""))).replace("\n", "<br/>"), styles["code"])]
        if block_type == "math":
            return [self._math_flowable(str(block.get("formula", "")), usable_width, math_cache), Spacer(1, 0.08 * inch)]
        if block_type == "table":
            return [self._table_flowable(block.get("rows", []), styles, usable_width), Spacer(1, 0.1 * inch)]
        return [Paragraph(self._inline_markup(str(block.get("text", ""))), styles["body"])]

    def _inline_markup(self, text: str) -> str:
        placeholders: dict[str, str] = {}

        def protect(pattern: str, transform: Any) -> None:
            nonlocal text

            def repl(match: re.Match[str]) -> str:
                key = f"@@DORJE{len(placeholders)}@@"
                placeholders[key] = transform(match)
                return key

            text = re.sub(pattern, repl, text, flags=re.S)

        protect(r"`([^`]+)`", lambda m: f"<font name='Courier'>{escape(m.group(1))}</font>")
        protect(r"\$([^$\n]+)\$", lambda m: escape(self._math_text_fallback(m.group(1))))
        text = escape(text)
        text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
        text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<i>\1</i>", text)
        text = re.sub(r"__([^_]+)__", r"<b>\1</b>", text)
        text = re.sub(r"(?<!_)_([^_]+)_(?!_)", r"<i>\1</i>", text)
        for key, value in placeholders.items():
            text = text.replace(key, value)
        return text

    def _math_flowable(self, formula: str, usable_width: float, math_cache: dict[str, bytes]) -> Any:
        normalized = self._normalize_math_formula(formula)
        try:
            if normalized not in math_cache:
                figure = Figure(figsize=(1, 1), dpi=220)
                figure.patch.set_alpha(0)
                figure.text(0, 0, f"${normalized}$", fontsize=16, color="#111827")
                output = BytesIO()
                figure.savefig(output, format="png", transparent=True, bbox_inches="tight", pad_inches=0.08)
                math_cache[normalized] = output.getvalue()
            image = ReportImage(BytesIO(math_cache[normalized]))
            image._restrictSize(usable_width * 0.96, 1.4 * inch)
            image.hAlign = "CENTER"
            return image
        except Exception as exc:  # matplotlib mathtext can fail on unsupported commands
            logger.warning("PDF math rendering failed for formula preview %r: %s", normalized[:120], exc)
            return Paragraph(escape(self._math_text_fallback(normalized)), self._pdf_styles()["body"])

    def _math_text_fallback(self, formula: str) -> str:
        text = self._normalize_math_formula(formula)
        replacements = {
            r"\frac": "",
            r"\sum": "Σ",
            r"\sqrt": "√",
            r"\bar{x}": "x̄",
            r"\bar{y}": "ȳ",
            r"\times": "×",
            r"\cdot": "·",
            r"\leq": "≤",
            r"\geq": "≥",
        }
        for source, target in replacements.items():
            text = text.replace(source, target)
        text = re.sub(r"\\([a-zA-Z]+)", r"\1", text)
        text = text.replace("{", "").replace("}", "")
        text = re.sub(r"\s+", " ", text)
        return text

    def _normalize_math_formula(self, formula: str) -> str:
        text = formula.strip().strip("$").strip()
        # AI and escaped transport paths sometimes double LaTeX backslashes.
        # MathText expects a single command prefix, e.g. \frac not \\frac.
        while "\\\\" in text:
            text = text.replace("\\\\", "\\")
        return text

    def _table_flowable(self, rows: list[list[Any]], styles: dict[str, ParagraphStyle], usable_width: float) -> Table:
        if not rows:
            return Table([[""]], colWidths=[usable_width])
        width = max(len(row) for row in rows)
        normalized = [(list(row) + [""] * width)[:width] for row in rows]
        col_widths = [usable_width / width] * width
        rendered_rows: list[list[Paragraph]] = []
        for row_index, row in enumerate(normalized):
            style = styles["table_head"] if row_index == 0 else styles["table_cell"]
            rendered_rows.append([Paragraph(self._inline_markup(str(cell)), style) for cell in row])
        table = Table(rendered_rows, repeatRows=1, hAlign="LEFT", colWidths=col_widths, splitByRow=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#047857")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5E1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        return table

    def export_docx(self, report_text: str, title: str = "DorjeAI Report", chart_assets: list | None = None) -> bytes:
        document = Document()
        document.add_heading("Lotus & Dorje", level=1)
        document.add_heading(title, level=2)
        document.add_paragraph(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}")

        for line in report_text.splitlines():
            stripped = line.strip()
            if not stripped:
                document.add_paragraph()
            elif stripped.startswith("# "):
                document.add_heading(stripped[2:], level=1)
            elif stripped.startswith("## "):
                document.add_heading(stripped[3:], level=2)
            elif stripped.startswith("### "):
                document.add_heading(stripped[4:], level=3)
            elif stripped.startswith("- "):
                document.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped.startswith("1. ") or stripped.startswith("2. ") or stripped.startswith("3. "):
                document.add_paragraph(stripped, style="List Number")
            elif stripped.startswith("|") and stripped.endswith("|"):
                cells = [cell.strip() for cell in stripped.split("|")[1:-1]]
                table = document.add_table(rows=1, cols=len(cells))
                table.style = "Table Grid"
                for index, cell in enumerate(cells):
                    table.cell(0, index).text = cell
            else:
                document.add_paragraph(stripped)

        for asset in chart_assets or []:
            image_data_url = getattr(asset, "image_data_url", "")
            if not image_data_url.startswith("data:image/"):
                continue
            try:
                document.add_page_break()
                document.add_heading(getattr(asset, "title", "Chart"), level=2)
                document.add_picture(BytesIO(base64.b64decode(image_data_url.split(",", 1)[1])), width=Inches(6.5))
                dataset = getattr(asset, "dataset", None)
                if dataset and dataset.columns and dataset.rows:
                    document.add_heading("Source data", level=3)
                    source_table = document.add_table(rows=1, cols=len(dataset.columns)); source_table.style = "Table Grid"
                    for index, column in enumerate(dataset.columns): source_table.cell(0, index).text = str(column)
                    for row in dataset.rows:
                        cells = source_table.add_row().cells
                        for index, value in enumerate(row[:len(cells)]): cells[index].text = str(value)
            except (ValueError, IndexError):
                continue

        section = document.sections[0]
        section.footer.paragraphs[0].text = "Generated by DorjeAI — Lotus & Dorje Enterprise AI Platform"
        section.footer.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

        buffer = BytesIO()
        document.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()

