'use client';

import Link from 'next/link';
import { BookOpen, Bot, ChartNoAxesColumn, FileText, LayoutDashboard, LockKeyhole, Mail, MessageSquareText, Mic, Paperclip, Settings, Sparkles } from 'lucide-react';
import AuthGuard from '@/components/AuthGuard';
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import Footer from '@/components/Footer';

const sections = [
  { icon: LayoutDashboard, title: 'Dashboard and application navigation', body: 'Dashboard provides the operating overview. Use Organizations for tenant-safe client records, Reports for reusable deliverables, and Open DorjeAI for analysis and content workflows.', steps: ['Review operating cards', 'Open Organizations or Reports', 'Launch DorjeAI from the header or dashboard', 'Ask Kamal to navigate after confirmation'] },
  { icon: Bot, title: 'DorjeAI workspace layout', body: 'The left panel owns navigation, the center owns conversation and outputs, the right panel owns current-chat context, and the fixed composer owns input and creation tools.', steps: ['Resize the left panel from its right edge', 'Hover over the right icon rail to expand it', 'Pin the right panel when persistent context is useful', 'Use the fixed composer without losing scroll position'] },
  { icon: Sparkles, title: 'Models and operating modes', body: 'Automatic routing selects an installed local model. Modes shape how answers are produced without changing tenant or connector security.', steps: ['Fast Chat for concise work', 'Deep Analysis for risks and recommendations', 'Statistics Mode for formulas, tables and charts', 'Report, Social and Email modes for reusable assets'] },
  { icon: Paperclip, title: 'Files and working context', body: 'Attach, drag, paste, photograph, or capture supported files. Extracted content remains linked to the current chat and is available in the context panel.', steps: ['Attach PDF, DOCX, spreadsheets, code, media or audio', 'Review file chips before sending', 'Ask for summary, extraction, comparison or analysis', 'Remove sensitive context when it is no longer needed'] },
  { icon: ChartNoAxesColumn, title: 'Tables, charts and images', body: 'DorjeAI turns user data into structured reusable assets. Generated tables preserve rows and columns; charts use supplied data; images render directly in chat.', steps: ['Convert output into a table', 'Copy to Excel or download XLSX/CSV', 'Create and export a chart', 'Generate, copy, download or hand off an image'] },
  { icon: MessageSquareText, title: 'Output reuse and exports', body: 'Every response provides context-aware actions. Copy, reuse as input, export, regenerate, email, publish socially, or continue through What’s next suggestions.', steps: ['Review generated content', 'Select the appropriate output action', 'Choose an export template when needed', 'Confirm any external action'] },
  { icon: Mic, title: 'Kamal text and voice control', body: 'Kamal answers application questions and understands simple navigation aliases. Voice mode repeats the interpreted intent and waits for spoken or clicked confirmation.', steps: ['Open Kamal and select Text or Voice', 'Say “Open Dashboard” or “Go to Dorje and type…”', 'Verify Kamal’s interpretation', 'Say Yes/No or select the confirmation button'] },
  { icon: Mail, title: 'Connectors, email and scheduling', body: 'Gmail uses per-user server-side OAuth tokens. Email, callback and call workflows are prepared first and sent only after review and confirmation.', steps: ['Connect Gmail in Connectors', 'Prepare a draft from DorjeAI or Kamal', 'Review recipient, agenda and content', 'Confirm the send; connect Calendar/Directory when available'] },
  { icon: LockKeyhole, title: 'Security and tenancy', body: 'Protected routes require a valid session. Organization data is tenant scoped. OAuth credentials stay encrypted on the server and never belong in browser storage.', steps: ['Sign in before using protected tools', 'Never paste credentials into chat', 'Use least-privilege connector scopes', 'Confirm sends, publishing and destructive actions'] },
  { icon: Settings, title: 'Troubleshooting', body: 'Most failures identify the unavailable layer: frontend, API authentication, Ollama, document extraction, image jobs, or OAuth configuration.', steps: ['Connection refused: start the relevant server', 'Credential error: sign in again', 'Model offline: start Ollama and verify models', 'Connector error: verify environment configuration'] },
];

export default function OperationsGuidePage() {
  return <AuthGuard><div className="flex min-h-screen bg-slate-50"><Sidebar /><div className="flex min-h-screen min-w-0 flex-1 flex-col"><Header title="Operations & UI/UX Guide" subtitle="Detailed setup, controls, workflows and security guidance for Lotus & Dorje." /><main className="flex-1 p-5 sm:p-7"><section className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 p-7 text-white shadow-xl"><div className="flex items-start gap-4"><span className="rounded-2xl bg-emerald-400/15 p-3 text-emerald-300"><BookOpen size={28} /></span><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-300">Application handbook</p><h1 className="mt-2 text-3xl font-semibold">Operate the platform with confidence</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Use this page as a practical reference. Kamal uses the same operating rules to explain features, navigate the application, and confirm actions safely.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/dorje-ai" className="rounded-xl bg-emerald-400 px-4 py-2.5 text-sm font-semibold text-emerald-950">Open DorjeAI</Link><Link href="/student-lad/connectors" className="rounded-xl border border-white/15 px-4 py-2.5 text-sm font-semibold text-white">Manage connectors</Link></div></div></div></section><div className="mt-6 grid gap-4 xl:grid-cols-2">{sections.map(({ icon: Icon, title, body, steps }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2.5 text-emerald-700"><Icon size={20} /></span><h2 className="font-semibold text-slate-900">{title}</h2></div><p className="mt-3 text-sm leading-6 text-slate-600">{body}</p><ol className="mt-4 space-y-2">{steps.map((step, index) => <li key={step} className="flex gap-3 text-sm text-slate-700"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xs font-semibold text-slate-600">{index + 1}</span><span className="pt-0.5">{step}</span></li>)}</ol></article>)}</div><div className="mt-6 rounded-2xl border border-sky-200 bg-sky-50 p-5"><div className="flex gap-3"><FileText className="shrink-0 text-sky-700" size={20} /><div><h2 className="font-semibold text-sky-950">Need guided help?</h2><p className="mt-1 text-sm text-sky-900">Open Kamal and ask “How do I use Statistics Mode?”, “Help me connect Gmail”, or “Take me to DorjeAI.” Kamal confirms operational actions before proceeding.</p></div></div></div></main><Footer /></div></div></AuthGuard>;
}
