'use client';

import { useEffect, useRef, useState, type CSSProperties, type PointerEvent as ReactPointerEvent } from 'react';
import Link from 'next/link';
import { AppWindow, Bot, ChevronRight, Cloud, Copy, FolderClock, HardDrive, Home, LogOut, MessageSquarePlus, MoreHorizontal, Pencil, Pin, PinOff, Settings, Star, Trash2 } from 'lucide-react';
import { deleteChatConversation, duplicateChatConversation, renameChatConversation, updateChatFlags, type StoredConversation } from '@/lib/chatHistory';
import type { WorkspaceView } from './WorkspacePanel';

type Props = { onNewChat: () => void; onLogout: () => void; active?: 'chat' | 'connectors' | 'templates'; view?: WorkspaceView; histories?: StoredConversation[]; onSelectHistory?: (conversation: StoredConversation) => void; onNavigate?: (view: WorkspaceView) => void; onHistoryChange?: (history: StoredConversation[]) => void };

const navItems = [
  { icon: Home, label: 'Home', view: 'chat' as const },
  { icon: FolderClock, label: 'Chat History', view: 'history' as const },
  { icon: AppWindow, label: 'My Apps', view: 'my-apps' as const },
  { icon: Settings, label: 'Settings', view: 'settings' as const },
];

export default function DorjeSidebar({ onNewChat, onLogout, active = 'chat', view = 'chat', histories = [], onSelectHistory, onNavigate, onHistoryChange }: Props) {
  const [panelWidth, setPanelWidth] = useState(280); const [pinned, setPinned] = useState(true); const [hovered, setHovered] = useState(false); const resizeRef = useRef({ startX: 0, startWidth: 280 });
  const recentHistories = histories.slice(0, 3);
  const expanded = pinned || hovered;
  const displayedWidth = expanded ? panelWidth : 70;
  useEffect(() => { const timer = window.setTimeout(() => { const stored = Number(window.localStorage.getItem('dorje_left_panel_width')); if (Number.isFinite(stored) && stored >= 220 && stored <= 380) setPanelWidth(stored); setPinned(window.localStorage.getItem('dorje_left_panel_pinned') !== 'false'); }, 0); return () => window.clearTimeout(timer); }, []);
  function resizeTo(width: number) { setPanelWidth(Math.min(380, Math.max(220, width))); }
  function beginResize(event: ReactPointerEvent<HTMLButtonElement>) { resizeRef.current = { startX: event.clientX, startWidth: panelWidth }; event.currentTarget.setPointerCapture(event.pointerId); }
  function moveResize(event: ReactPointerEvent<HTMLButtonElement>) { if (!event.currentTarget.hasPointerCapture(event.pointerId)) return; resizeTo(resizeRef.current.startWidth + event.clientX - resizeRef.current.startX); }
  function finishResize(event: ReactPointerEvent<HTMLButtonElement>) { if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); window.localStorage.setItem('dorje_left_panel_width', String(panelWidth)); }
  function togglePin() { const next = !pinned; setPinned(next); if (!next) setHovered(false); window.localStorage.setItem('dorje_left_panel_pinned', String(next)); }
  function rename(chat: StoredConversation) { const title = window.prompt('Rename conversation', chat.title)?.trim(); if (title) onHistoryChange?.(renameChatConversation(chat.id, title)); }
  function remove(chat: StoredConversation) { if (window.confirm(`Delete “${chat.title}”?`)) onHistoryChange?.(deleteChatConversation(chat.id)); }
  return <aside aria-label="Workspace AI navigation" onMouseEnter={() => setHovered(true)} onMouseLeave={() => setHovered(false)} onFocus={() => setHovered(true)} onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget)) setHovered(false); }} className="dorje-sidebar relative flex w-full shrink-0 flex-col border-b border-slate-800 bg-slate-950/95 p-2.5 transition-[width] duration-200 lg:h-full lg:w-[70px] lg:border-b-0 lg:border-r xl:p-4" style={{ '--dorje-left-width': `${displayedWidth}px` } as CSSProperties}>
    <div className={`flex items-center gap-2 ${expanded ? 'justify-between' : 'justify-center'}`}>
      <Link href="/student-lad" className={`flex min-w-0 items-center gap-3 rounded-xl px-1 py-1 ${expanded ? 'justify-start' : 'justify-center'}`} title="Return to Student-LAD"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-400 to-teal-600 text-slate-950 shadow-lg shadow-emerald-950/30"><Bot size={21} /></span>{expanded ? <div className="hidden min-w-0 xl:block"><p className="truncate text-xs font-semibold uppercase tracking-[0.2em] text-emerald-300">Lotus & Dorje</p><h1 className="truncate text-base font-semibold text-white">Workspace AI</h1><p className="text-[10px] text-slate-500">Dorje chat, apps and settings</p></div> : null}</Link>
      {expanded ? <button type="button" onClick={togglePin} className="hidden h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-slate-800 text-slate-400 transition hover:border-emerald-400/40 hover:bg-emerald-500/10 hover:text-emerald-200 xl:flex" aria-pressed={pinned} aria-label={pinned ? 'Unpin Workspace AI panel' : 'Pin Workspace AI panel'} title={pinned ? 'Unpin panel' : 'Pin panel'}>{pinned ? <PinOff size={15} /> : <Pin size={15} />}</button> : null}
    </div>
    <button type="button" onClick={onNewChat} className="mt-3 flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-500 px-3 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400 xl:mt-5"><MessageSquarePlus size={18} /><span className={`hidden ${expanded ? 'xl:inline' : 'xl:hidden'}`}>New Chat</span></button>
    {!expanded ? <button type="button" onClick={togglePin} className="mt-2 hidden min-h-10 items-center justify-center rounded-xl border border-slate-800 text-slate-500 transition hover:bg-slate-900 hover:text-emerald-200 xl:flex" aria-pressed={pinned} aria-label="Pin Workspace AI panel" title="Pin Workspace AI"><Pin size={15} /></button> : null}
    <nav className="mt-2 flex gap-1 overflow-x-auto lg:mt-5 lg:flex-col lg:overflow-visible">
      {navItems.map(({ icon: Icon, label, view: itemView }) => label === 'Home' ? <Link key={label} href="/student-lad" className={`sidebar-item ${expanded ? '' : 'xl:justify-center'}`} title="Student-LAD Home"><Icon size={18} /><span className={`whitespace-nowrap lg:hidden ${expanded ? 'xl:inline' : 'xl:hidden'}`}>{label}</span></Link> : label === 'Settings' ? <Link key={label} href="/student-lad/settings" className={`sidebar-item ${expanded ? '' : 'xl:justify-center'}`} title="Student-LAD Settings"><Icon size={18} /><span className={`whitespace-nowrap lg:hidden ${expanded ? 'xl:inline' : 'xl:hidden'}`}>{label}</span></Link> : onNavigate ? <button key={label} type="button" onClick={() => onNavigate(itemView)} className={`sidebar-item ${expanded ? '' : 'xl:justify-center'} ${active === 'chat' && view === itemView ? 'sidebar-item-active' : ''}`} title={label}><Icon size={18} /><span className={`whitespace-nowrap lg:hidden ${expanded ? 'xl:inline' : 'xl:hidden'}`}>{label}</span></button> : <Link key={label} href={`/dorje-ai?view=${itemView}`} className={`sidebar-item ${expanded ? '' : 'xl:justify-center'}`} title={label}><Icon size={18} /><span className={`whitespace-nowrap lg:hidden ${expanded ? 'xl:inline' : 'xl:hidden'}`}>{label}</span></Link>)}
    </nav>
    {active === 'chat' && expanded ? <section className="mt-5 hidden min-h-0 flex-1 xl:flex xl:flex-col"><div className="flex items-center justify-between px-2"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">Recent conversations</p><ChevronRight size={14} className="text-slate-600" /></div><div className="mt-2 min-h-0 space-y-1 overflow-y-auto">{recentHistories.length ? recentHistories.map((chat) => <div key={chat.id} className="group/history relative rounded-xl hover:bg-slate-900"><button type="button" onClick={() => onSelectHistory?.(chat)} className="block w-full px-3 py-2.5 pr-9 text-left"><span className="flex items-center gap-1 text-xs font-medium text-slate-300">{chat.pinned ? <Pin size={11} className="text-emerald-300" /> : null}{chat.favorite ? <Star size={11} className="fill-amber-300 text-amber-300" /> : null}<span className="truncate">{chat.title}</span></span><span className="mt-1 block text-[10px] text-slate-600">{new Date(chat.updatedAt).toLocaleDateString()}</span></button><details className="absolute right-1 top-2"><summary className="flex h-7 w-7 cursor-pointer list-none items-center justify-center rounded-lg text-slate-500 opacity-0 hover:bg-slate-800 group-hover/history:opacity-100"><MoreHorizontal size={15} /></summary><div className="absolute right-0 top-8 z-30 w-40 rounded-xl border border-slate-700 bg-slate-900 p-1 shadow-2xl"><HistoryAction icon={Pencil} label="Rename" onClick={() => rename(chat)} /><HistoryAction icon={Pin} label={chat.pinned ? 'Unpin' : 'Pin'} onClick={() => onHistoryChange?.(updateChatFlags(chat.id, { pinned: !chat.pinned }))} /><HistoryAction icon={Star} label={chat.favorite ? 'Unfavorite' : 'Favorite'} onClick={() => onHistoryChange?.(updateChatFlags(chat.id, { favorite: !chat.favorite }))} /><HistoryAction icon={Copy} label="Duplicate" onClick={() => onHistoryChange?.(duplicateChatConversation(chat.id))} /><HistoryAction icon={Trash2} label="Delete" danger onClick={() => remove(chat)} /></div></details></div>) : <div className="rounded-xl border border-dashed border-slate-800 p-4 text-center"><FolderClock size={20} className="mx-auto text-slate-600" /><p className="mt-2 text-xs text-slate-600">Recent chats appear here.</p></div>}</div></section> : <div className="flex-1" />}
    <div className="mt-auto hidden space-y-2 lg:block">{expanded ? <div className="hidden rounded-xl border border-emerald-400/10 bg-emerald-500/5 p-3 xl:block"><div className="flex items-center gap-2 text-xs text-emerald-200"><HardDrive size={14} />Local Mode <span className="ml-auto">On</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-[18%] rounded-full bg-emerald-400" /></div><p className="mt-1.5 text-[10px] text-slate-500">Browser storage · 18% used</p><div className="mt-2 flex items-center gap-2 text-[10px] text-slate-500"><Cloud size={12} />Cloud sync via connectors</div><p className="mt-2 text-[9px] text-slate-600">DorjeAI Workspace · v2.0</p></div> : null}<button type="button" onClick={onLogout} className={`sidebar-item w-full text-rose-300 ${expanded ? '' : 'xl:justify-center'}`} title="Logout"><LogOut size={18} /><span className={`hidden ${expanded ? 'xl:inline' : 'xl:hidden'}`}>Logout</span></button></div>
    {expanded ? <button type="button" role="separator" aria-label="Resize left navigation" aria-orientation="vertical" aria-valuemin={220} aria-valuemax={380} aria-valuenow={panelWidth} onPointerDown={beginResize} onPointerMove={moveResize} onPointerUp={finishResize} onPointerCancel={finishResize} onKeyDown={(event) => { if (event.key === 'ArrowLeft') resizeTo(panelWidth - 10); if (event.key === 'ArrowRight') resizeTo(panelWidth + 10); }} className="panel-resizer panel-resizer-right hidden xl:block" title="Drag to resize navigation" /> : null}
  </aside>;
}

function HistoryAction({ icon: Icon, label, onClick, danger = false }: { icon: typeof Pencil; label: string; onClick: () => void; danger?: boolean }) { return <button type="button" onClick={onClick} className={`flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-xs hover:bg-slate-800 ${danger ? 'text-rose-300' : 'text-slate-300'}`}><Icon size={14} />{label}</button>; }
