'use client';

import { useMemo, useState } from 'react';
import Image from 'next/image';
import { Bookmark, Check, Clipboard, Copy, Download, FileSpreadsheet, FileText, ImageUp, Link2, Mail, MoreHorizontal, Pencil, Presentation, RefreshCw, Save, Share2, Sparkles, Table2, Trash2, UserRound, WandSparkles } from 'lucide-react';
import FormattedContent from './FormattedContent';
import StructuredTableView, { type StructuredTableData } from './StructuredTableView';

type Payload = { content: string; imageUrl?: string };
type DorjeMessageProps = {
  role: 'user' | 'assistant'; content: string; imageUrl?: string; table?: StructuredTableData; model?: string;
  onSavePdf?: () => void; onCreateEmail?: (payload: Payload) => void; onCreateSocial?: (payload: Payload) => void;
  onConvertTable?: () => void; onEdit?: (content?: string) => void; onRegenerate?: () => void; onUseAsInput?: (content?: string) => void;
  onFollowUp?: (prompt: string) => void; onDelete?: () => void; tableLoading?: boolean; versions?: string[];
  attachments?: { name: string; type: string }[]; chartOpen?: boolean; enhancedPrompt?: string; originalPrompt?: string;
  onImageVariation?: (action: string) => void;
};

function suggestions(content: string, hasTable: boolean, hasImage: boolean) {
  if (hasImage) return ['Create variations', 'Use in a report', 'Write a LinkedIn post', 'Create an email'];
  if (hasTable || /\b(data|statistics|metrics|revenue|cost|growth)\b/i.test(content)) return ['Generate charts', 'Convert to Excel', 'Explain the findings', 'Create executive report'];
  if (/\b(risk|strategy|roadmap|implementation|plan)\b/i.test(content)) return ['Identify risks', 'Estimate cost', 'Build project plan', 'Compare alternatives'];
  return ['Explain further', 'Summarize', 'Create executive report', 'Ask a deeper question'];
}

export default function DorjeMessage({ role, content, imageUrl, table, model, onSavePdf, onCreateEmail, onCreateSocial, onConvertTable, onEdit, onRegenerate, onUseAsInput, onFollowUp, onDelete, tableLoading, versions, attachments, chartOpen, enhancedPrompt, originalPrompt, onImageVariation }: DorjeMessageProps) {
  const isUser = role === 'user'; const [copied, setCopied] = useState(false); const [bookmarked, setBookmarked] = useState(false); const [imageName, setImageName] = useState('dorje-generated-image.png'); const [editing, setEditing] = useState(false); const [draftContent, setDraftContent] = useState(content);
  const nextSuggestions = useMemo(() => suggestions(content, Boolean(table), Boolean(imageUrl)), [content, imageUrl, table]);
  async function copyContent() {
    if (imageUrl && 'ClipboardItem' in window) { const image = await fetch(imageUrl).then((response) => response.blob()); await navigator.clipboard.write([new ClipboardItem({ 'image/png': image })]); }
    else await navigator.clipboard.writeText(content);
    setCopied(true); window.setTimeout(() => setCopied(false), 1500);
  }
  function downloadImage() { if (!imageUrl) return; const anchor = document.createElement('a'); anchor.href = imageUrl; anchor.download = imageName; anchor.click(); }
  async function share() { if (navigator.share) await navigator.share({ title: 'DorjeAI output', text: content }); else await navigator.clipboard.writeText(content); }
  function renameImage() { const name = window.prompt('Rename generated image', imageName)?.trim(); if (name) setImageName(name.endsWith('.png') ? name : `${name}.png`); }
  return <article className={`group flex items-start gap-3 ${isUser ? 'flex-row-reverse' : ''}`}>
    {isUser ? <div className="avatar-chip" aria-label="You"><UserRound size={18} /></div> : <Image src="/dorje-avatar.svg" alt="Dorje AI" width={38} height={38} className="h-10 w-10 shrink-0 rounded-xl shadow-lg shadow-emerald-950/30" />}
    <div className={`dorje-message-card min-w-0 max-w-[calc(100%-3.25rem)] rounded-2xl border px-4 py-3.5 text-sm leading-7 shadow-sm sm:max-w-[88%] lg:max-w-[840px] ${isUser ? 'border-emerald-400/20 bg-emerald-500/10 text-emerald-50' : 'border-slate-800 bg-slate-900/75 text-slate-100'}`}>
      {versions?.length ? <div className="mb-1 text-[10px] font-semibold uppercase tracking-[0.2em] opacity-60">Version {versions.length + 1}</div> : null}
      {editing ? <div className="space-y-2"><textarea autoFocus value={draftContent} onChange={(event) => setDraftContent(event.target.value)} onKeyDown={(event) => { if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') { event.preventDefault(); const clean = draftContent.trim(); if (clean && clean !== content) onEdit?.(clean); setEditing(false); } if (event.key === 'Escape') { setDraftContent(content); setEditing(false); } }} className="min-h-28 w-full resize-y rounded-xl border border-emerald-400/30 bg-slate-950/80 px-3 py-2 text-sm leading-6 text-white outline-none focus:border-emerald-300" aria-label="Edit posted message inline" /><div className="flex flex-wrap items-center gap-2 text-xs"><button type="button" onClick={() => { const clean = draftContent.trim(); if (clean && clean !== content) onEdit?.(clean); setEditing(false); }} className="rounded-lg bg-emerald-400 px-3 py-1.5 font-semibold text-slate-950">Save & regenerate</button><button type="button" onClick={() => { setDraftContent(content); setEditing(false); }} className="rounded-lg border border-slate-700 px-3 py-1.5 font-semibold text-slate-300">Cancel</button><span className="text-slate-500">⌘Enter save · Esc cancel</span></div></div> : <FormattedContent content={content} />}
      {attachments?.length ? <div className="mt-3 flex flex-wrap gap-2">{attachments.map((attachment, index) => <span key={`${attachment.name}-${index}`} className="asset-pill" title={attachment.type}><FileText size={13} /><span className="truncate">{attachment.name}</span></span>)}</div> : null}
      {table ? <StructuredTableView table={table} initialShowChart={chartOpen} onUseInPrompt={(value) => onUseAsInput?.(value)} onUseInEmail={(value) => onCreateEmail?.({ content: value })} onUseInSocial={(value) => onCreateSocial?.({ content: value })} /> : null}
      {imageUrl ? <section className="mt-4 overflow-hidden rounded-2xl border border-slate-700 bg-slate-950"><div className="flex flex-wrap items-center gap-1 border-b border-slate-800 p-2"><ImageTool icon={Download} label="Download" onClick={downloadImage} /><ImageTool icon={Clipboard} label="Copy image" onClick={() => void copyContent()} /><ImageTool icon={Pencil} label="Edit prompt" onClick={() => onImageVariation?.('Edit prompt')} /><ImageTool icon={ImageUp} label="Upscale" onClick={() => onImageVariation?.('Upscale high resolution')} /><ImageTool icon={RefreshCw} label="Regenerate" onClick={onRegenerate} /><details className="relative ml-auto"><summary className="icon-control cursor-pointer list-none" title="More image actions"><MoreHorizontal size={17} /></summary><div className="action-menu right-0"><MenuAction icon={WandSparkles} label="Create variations" onClick={() => onImageVariation?.('Create four creative variations')} /><MenuAction icon={FileText} label="Use in report" onClick={() => onFollowUp?.('Create a report using this image')} /><MenuAction icon={Sparkles} label="Use in social" onClick={() => onCreateSocial?.({ content, imageUrl })} /><MenuAction icon={Mail} label="Use in email" onClick={() => onCreateEmail?.({ content, imageUrl })} /><MenuAction icon={Pencil} label="Rename" onClick={renameImage} /><MenuAction icon={Save} label="Save" onClick={downloadImage} /><MenuAction icon={Trash2} label="Delete" danger onClick={onDelete} /></div></details></div><Image src={imageUrl} alt="Generated by Dorje AI" width={1024} height={1024} loading="lazy" unoptimized className="block max-h-[min(65vh,720px)] w-full object-contain" /><details className="border-t border-slate-800"><summary className="cursor-pointer px-3 py-2 text-xs font-medium text-slate-400">View metadata and prompt history</summary><div className="grid gap-2 border-t border-slate-800 p-3 text-xs text-slate-400 sm:grid-cols-2"><p><strong className="text-slate-300">File</strong><br />{imageName}</p><p><strong className="text-slate-300">Model</strong><br />{model || 'Local image model'}</p><p className="sm:col-span-2"><strong className="text-slate-300">Original prompt</strong><br />{originalPrompt || 'Not recorded'}</p>{enhancedPrompt ? <p className="sm:col-span-2"><strong className="text-slate-300">Enhanced prompt</strong><br />{enhancedPrompt}</p> : null}</div></details></section> : enhancedPrompt ? <details open className="mt-3 rounded-xl border border-violet-300/15 bg-violet-500/5"><summary className="cursor-pointer px-3 py-2 text-xs font-semibold text-violet-200">Enhanced image prompt</summary><p className="border-t border-violet-300/10 p-3 text-xs leading-5 text-slate-300">{enhancedPrompt}</p></details> : null}
      {content ? <div className="message-action-bar" aria-label="Output actions"><Action icon={copied ? Check : Clipboard} label={copied ? 'Copied' : 'Copy'} onClick={() => void copyContent()} /><Action icon={Table2} label={tableLoading ? 'Converting' : 'Table'} disabled={tableLoading} onClick={onConvertTable} /><Action icon={Link2} label="Use in chat" onClick={() => onUseAsInput?.()} />{isUser ? <Action icon={Pencil} label="Edit" onClick={() => { setDraftContent(content); setEditing(true); }} /> : <><Action icon={FileText} label="PDF" onClick={onSavePdf} /><Action icon={Mail} label="Email" onClick={() => onCreateEmail?.({ content, imageUrl })} /><Action icon={Sparkles} label="Social" onClick={() => onCreateSocial?.({ content, imageUrl })} /><Action icon={RefreshCw} label="Regenerate" onClick={onRegenerate} /><details className="relative"><summary className="output-action cursor-pointer list-none" title="More actions"><MoreHorizontal size={15} /><span>More</span></summary><div className="action-menu right-0"><MenuAction icon={FileText} label="Export DOCX" onClick={() => onFollowUp?.('Export this as a DOCX document')} /><MenuAction icon={Presentation} label="Create presentation" onClick={() => onFollowUp?.('Create a presentation from this')} /><MenuAction icon={FileSpreadsheet} label="Export Excel" onClick={onConvertTable} /><MenuAction icon={Save} label="Save report" onClick={() => setBookmarked(true)} /><MenuAction icon={Bookmark} label={bookmarked ? 'Bookmarked' : 'Bookmark'} onClick={() => setBookmarked((value) => !value)} /><MenuAction icon={Share2} label="Share" onClick={() => void share()} /><MenuAction icon={Copy} label="Duplicate" onClick={() => onUseAsInput?.(content)} /><MenuAction icon={Trash2} label="Delete" danger onClick={onDelete} /></div></details></>}</div> : null}
      {!isUser && content ? <div className="mt-4"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">What&apos;s next?</p><div className="mt-2 flex flex-wrap gap-2">{nextSuggestions.map((prompt) => <button key={prompt} type="button" onClick={() => onFollowUp?.(prompt)} className="suggestion-chip">{prompt}</button>)}</div></div> : null}
    </div>
  </article>;
}

function Action({ icon: Icon, label, onClick, disabled }: { icon: typeof Clipboard; label: string; onClick?: () => void; disabled?: boolean }) { return <button type="button" disabled={disabled} onClick={onClick} className="output-action" title={label}><Icon size={15} /><span>{label}</span></button>; }
function ImageTool({ icon: Icon, label, onClick }: { icon: typeof Download; label: string; onClick?: () => void }) { return <button type="button" onClick={onClick} className="image-tool" title={label}><Icon size={15} /><span className="hidden sm:inline">{label}</span></button>; }
function MenuAction({ icon: Icon, label, onClick, danger = false }: { icon: typeof Save; label: string; onClick?: () => void; danger?: boolean }) { return <button type="button" onClick={onClick} className={`menu-action ${danger ? 'text-rose-300' : ''}`}><Icon size={14} />{label}</button>; }
