'use client';

import { useState } from 'react';
import { API_BASE_URL, authenticatedFetch, authorizationHeaders } from '@/lib/api';

export default function ReportStudio({ context }: { context: string }) {
  const [request, setRequest] = useState('Create an executive consulting report'); const [report, setReport] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const payload = () => ({ message: request, context, history: [], files: [] });
  async function generate() { setLoading(true); setError(''); try { const response = await authenticatedFetch(`${API_BASE_URL}/api/v1/dorje-ai/report`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...authorizationHeaders() }, body: JSON.stringify(payload()) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Unable to generate report.'); setReport(data.report || ''); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to generate report.'); } finally { setLoading(false); } }
  async function download(format: 'pdf' | 'docx') { const response = await authenticatedFetch(`${API_BASE_URL}/api/v1/dorje-ai/report/${format}`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...authorizationHeaders() }, body: JSON.stringify(payload()) }); if (!response.ok) return setError(`Unable to download ${format.toUpperCase()}.`); const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = `dorje-report.${format}`; link.click(); URL.revokeObjectURL(url); }
  function downloadText() { const url = URL.createObjectURL(new Blob([report], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = 'dorje-report.txt'; link.click(); URL.revokeObjectURL(url); }
  return <div className="space-y-3"><textarea className="field min-h-20" value={request} onChange={(e) => setRequest(e.target.value)} /><button type="button" onClick={generate} disabled={loading || !request.trim()} className="action-primary">{loading ? 'Generating…' : 'Generate Consulting Report'}</button>{error ? <p className="text-xs text-rose-300">{error}</p> : null}<textarea className="field min-h-64" placeholder="Report preview" value={report} onChange={(e) => setReport(e.target.value)} /><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => download('pdf')} className="action-secondary">Download PDF</button><button type="button" onClick={() => download('docx')} className="action-secondary">Download DOCX</button><button type="button" disabled={!report} onClick={downloadText} className="action-secondary">Export Summary</button><button type="button" disabled className="action-disabled">Save Report</button></div></div>;
}
