from io import BytesIO
import unittest

from pypdf import PdfReader

from app.services.report_export_service import DorjeReportExporter


class ReportExportServiceTests(unittest.TestCase):
    def setUp(self):
        self.exporter = DorjeReportExporter()

    def reader_for(self, text: str) -> PdfReader:
        pdf = self.exporter.export_pdf(text, title="PDF Export Test")
        self.assertTrue(pdf.startswith(b"%PDF"))
        return PdfReader(BytesIO(pdf))

    def extracted_text(self, reader: PdfReader) -> str:
        return "\n".join(page.extract_text() or "" for page in reader.pages)

    def test_markdown_controls_are_rendered_not_printed(self):
        reader = self.reader_for(
            """# Main Result
## Findings
This is **bold** and *italic* with `code`.
- First bullet
1. First numbered
> Evidence-backed note
"""
        )
        text = self.extracted_text(reader)
        self.assertIn("Main Result", text)
        self.assertIn("Findings", text)
        self.assertIn("bold", text)
        self.assertIn("italic", text)
        self.assertNotIn("**", text)
        self.assertNotIn("`code`", text)
        self.assertNotIn("> Evidence", text)

    def test_inline_and_display_math_do_not_leak_latex_commands(self):
        reader = self.reader_for(
            r"""Inline formula $r = 0.85$ should be readable.

$$r = \frac{\sum (x_i-\bar{x})(y_i-\bar{y})}
{\sqrt{\sum (x_i-\bar{x})^2\sum (y_i-\bar{y})^2}}$$
"""
        )
        text = self.extracted_text(reader)
        self.assertIn("Inline formula", text)
        for raw in ["$$", r"\frac", r"\sum", r"\bar", "{", "}"]:
            self.assertNotIn(raw, text)

    def test_escaped_display_math_is_normalized_before_rendering(self):
        reader = self.reader_for(r"$$r = \\frac{\\sum x_i}{\\sqrt{\\sum y_i^2}}$$")
        text = self.extracted_text(reader)
        for raw in ["$$", r"\\frac", r"\frac", r"\\sum", r"\sum", r"\\sqrt", r"\sqrt"]:
            self.assertNotIn(raw, text)

    def test_math_failure_uses_clean_fallback(self):
        reader = self.reader_for(r"$$\definitelyUnsupportedCommand{x} + 1$$")
        text = self.extracted_text(reader)
        self.assertNotIn("$$", text)
        self.assertNotIn("\\", text)
        self.assertIn("definitelyUnsupportedCommand", text)

    def test_long_markdown_table_spans_pages_without_raw_markers(self):
        rows = ["| Item | Detail |", "| --- | --- |"]
        for index in range(1, 80):
            rows.append(f"| Row {index} | This is a long wrapped cell value with **bold** text and inline $x_{index}$ content repeated repeated repeated. |")
        reader = self.reader_for("\n".join(rows))
        text = self.extracted_text(reader)
        self.assertGreaterEqual(len(reader.pages), 2)
        self.assertIn("Row 1", text)
        self.assertIn("Row 79", text)
        self.assertNotIn("| --- |", text)
        self.assertNotIn("**bold**", text)

    def test_page_numbers_include_total_count_for_long_documents(self):
        reader = self.reader_for("\n\n".join(f"## Section {index}\n" + ("Body text. " * 160) for index in range(1, 55)))
        text = self.extracted_text(reader)
        self.assertGreaterEqual(len(reader.pages), 10)
        self.assertIn(f"Page 1 of {len(reader.pages)}", text)
        self.assertIn(f"Page {len(reader.pages)} of {len(reader.pages)}", text)

    def test_pdf_has_no_pink_or_full_page_border_commands(self):
        pdf = self.exporter.export_pdf("Simple body text.", title="No Border")
        self.assertNotIn(b"EC4899", pdf)
        self.assertNotIn(b"roundRect", pdf)
        reader = PdfReader(BytesIO(pdf))
        text = self.extracted_text(reader)
        self.assertIn("Generated by DorjeAI | Lotus & Dorje", text)
        self.assertIn("Page 1 of 1", text)

    def test_unicode_text_exports_without_crashing(self):
        reader = self.reader_for("Unicode check: café, résumé, Δ, π, नमस्ते, 你好.")
        text = self.extracted_text(reader)
        self.assertIn("Unicode check", text)


if __name__ == "__main__":
    unittest.main()
