'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Eye, EyeOff, Pencil, Trash2, XCircle } from 'lucide-react';
import { apiFetch } from '@/lib/api';

type Item={id:string;batch_id?:string;version:number;domain:string;type:string;summary:string;key_date?:string;related_area:string;related_item:string;suggested_action:string;reminder_recommended:boolean;reminder_status:string;priority:string;source_type:string;source_reference?:string;policy_applied:string;confidence:number;status:string;created_at:string;updated_at:string;metadata?:{why?:string;raw_retained?:boolean;sensitive?:boolean};audit_events?:Array<{action:string;timestamp:string}>};
type Reminder={id:string;context_item_id?:string;title:string;due_at?:string;reminder_date?:string;priority:string;status:string;official_verification_required:boolean;disclaimer?:string};
type Source={document_id:string;title:string;source_kind:string;physical_location:string;domain:string;last_indexed_at:string;policy_binding:string;index_status:string};
type Batch={id:string;source_reference?:string;item_count:number;approved_count:number;denied_count:number;status:string};
type History={id:string;item_id:string;action:string;old_status?:string;new_status?:string;timestamp:string;actor:string;notes?:string};
type ReviewTab='Needs Review'|'Saved Information'|'Denied'|'Archived'|'Reminders'|'Sources'|'History';
const tabs:ReviewTab[]=['Needs Review','Saved Information','Denied','Archived','Reminders','Sources','History'];

export default function CEDAReviewWorkspace(){
 const [tab,setTab]=useState<ReviewTab>('Needs Review'); const [items,setItems]=useState<Item[]>([]); const [reminders,setReminders]=useState<Reminder[]>([]); const [sources,setSources]=useState<Source[]>([]); const [batches,setBatches]=useState<Batch[]>([]); const [history,setHistory]=useState<History[]>([]); const [selected,setSelected]=useState<Set<string>>(new Set()); const [notice,setNotice]=useState(''); const [error,setError]=useState('');
 const load=useCallback(async()=>{try{const [nextItems,nextReminders,nextSources,nextBatches,nextHistory]=await Promise.all([apiFetch<Item[]>('/api/v1/ceda/items'),apiFetch<{items:Reminder[]}>('/api/v1/ceda/reminders'),apiFetch<Source[]>('/api/v1/wkim/catalog'),apiFetch<Batch[]>('/api/v1/ceda/batches'),apiFetch<History[]>('/api/v1/ceda/item-history')]);setItems(nextItems);setReminders(nextReminders.items);setSources(nextSources);setBatches(nextBatches);setHistory(nextHistory);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load Review & Save.')}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const pendingCount=items.filter(item=>item.status==='pending_review').length;
 const visible=useMemo(()=>{if(tab==='Needs Review')return items.filter(item=>item.status==='pending_review');if(tab==='Saved Information')return items.filter(item=>item.status==='approved');if(tab==='Denied')return items.filter(item=>item.status==='denied');if(tab==='Archived')return items.filter(item=>item.status==='archived'||item.status==='deleted'||item.status==='superseded');return items},[items,tab]);
 const visibleIds=visible.map(item=>item.id); const allVisibleSelected=visibleIds.length>0&&visibleIds.every(id=>selected.has(id));
 function toggleAll(checked:boolean){setSelected(checked?new Set(visibleIds):new Set())}
 async function transition(item:Item,target:'approve'|'deny'|'delete'|'archive'){if((target==='delete'||target==='deny')&&!window.confirm(`${target==='delete'?'Delete':'Deny'} “${item.summary}”? It will not be used by Kamal or DorjeAI.`))return;try{await apiFetch(`/api/v1/ceda/items/${item.id}/${target}`,{method:'POST'});setSelected(next=>{const copy=new Set(next);copy.delete(item.id);return copy});setNotice(target==='approve'?'Saved information is now available to Kamal and DorjeAI.':`Item ${target}d.`);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to update item.')}}
 async function bulk(target:'approve'|'deny'){if(!selected.size)return;try{await apiFetch(`/api/v1/ceda/items/bulk-${target}`,{method:'POST',body:JSON.stringify({item_ids:[...selected]})});setNotice(`${selected.size} item${selected.size===1?'':'s'} ${target==='approve'?'saved':'denied'}.`);setSelected(new Set());await load()}catch(reason){setError(reason instanceof Error?reason.message:'Bulk action failed.')}}
 async function edit(item:Item){const summary=window.prompt('Edit the clean summary. The original version will be preserved.',item.summary)?.trim();if(!summary)return;const keyDate=window.prompt('Edit the key date, or leave blank.',item.key_date||'')?.trim()||null;try{await apiFetch(`/api/v1/ceda/items/${item.id}/edit-copy`,{method:'POST',body:JSON.stringify({changes:{summary,key_date:keyDate}})});setNotice('Edited copy created. Original record preserved as Superseded.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to create edited copy.')}}
 async function createReminder(item:Item){const option=window.prompt('Reminder: same_day, 1_day, 3_days, 7_days, 14_days, or default_academic','7_days')?.trim();if(!option)return;try{await apiFetch(`/api/v1/ceda/reminders/from-context/${item.id}`,{method:'POST',body:JSON.stringify({option})});setNotice('Reminder created from approved information.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to create reminder.')}}
 return <main className="mx-auto max-w-7xl space-y-5 pb-24" aria-label="Review and Save">
  <header className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-700">Review &amp; Save</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">Choose what Dorje AI may save and use later.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Clean structured information only. Nothing becomes saved information until you approve it. Raw chat, RTF, OCR noise, and temporary parsing are discarded.</p></header>
  <CedaLifecycle pending={pendingCount} saved={items.filter(item=>item.status==='approved').length} history={history.length} />
  <nav aria-label="Review tabs" className="overflow-x-auto rounded-2xl border border-slate-200 bg-white px-2 shadow-sm"><div className="flex min-w-max gap-1 py-2">{tabs.map(value=><button key={value} type="button" onClick={()=>{setTab(value);setSelected(new Set())}} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold transition ${tab===value?'bg-slate-950 text-white':'text-slate-500 hover:bg-slate-100 hover:text-slate-900'}`}>{value}{value==='Needs Review'?<span className="rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-black text-amber-800">{pendingCount}</span>:null}</button>)}</div></nav>
  {error?<p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>:null}{notice?<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>:null}
  {(tab==='Needs Review'||tab==='Saved Information'||tab==='Denied'||tab==='Archived')?<section className="space-y-3"><div className="rounded-[24px] border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><label className="inline-flex items-center gap-3 text-sm font-semibold text-slate-700"><input type="checkbox" checked={allVisibleSelected} onChange={event=>toggleAll(event.target.checked)} className="h-4 w-4 accent-emerald-600"/>Select all visible</label><p className="text-xs text-slate-500">{visible.length} item{visible.length===1?'':'s'} in {tab}</p></div>{selected.size?<div className="flex flex-wrap items-center gap-3 border-b border-emerald-100 bg-emerald-50 px-4 py-3 text-sm"><strong className="text-emerald-950">{selected.size} selected</strong><button type="button" onClick={()=>void bulk('approve')} className="rounded-xl bg-emerald-700 px-3 py-2 text-xs font-semibold text-white hover:bg-emerald-800">Approve all</button><button type="button" onClick={()=>void bulk('deny')} className="rounded-xl border border-rose-200 bg-white px-3 py-2 text-xs font-semibold text-rose-700">Deny all</button><button type="button" onClick={()=>setSelected(new Set())} className="text-xs font-semibold text-slate-600 underline-offset-2 hover:underline">Clear selection</button></div>:null}<ReviewTable items={visible} selected={selected} setSelected={setSelected} onTransition={transition} onEdit={edit} onReminder={createReminder}/></div>{tab==='Needs Review'&&batches.length?<p className="text-xs text-slate-600">Latest extraction: Dorje AI found {batches[0].item_count} useful item{batches[0].item_count===1?'':'s'} from {batches[0].source_reference||'the submitted source'}.</p>:null}</section>:null}
  {tab==='Reminders'?<ReminderPlanner reminders={reminders}/>:null}{tab==='Sources'?<SourceTable sources={sources}/>:null}{tab==='History'?<HistoryTable history={history}/>:null}</main>
}

function CedaLifecycle({pending,saved,history}:{pending:number;saved:number;history:number}){const stages=[['Capture','Files, chat, voice'],['Extract','Clean facts only'],['Review',`${pending} waiting`],['Approve',`${saved} saved`],['Context','Policy-bound'],['Reason','Relevant only'],['Action','Confirmed first'],['Learn',`${history} events`],['Update','Versioned']];return <section className="rounded-[28px] border border-emerald-100 bg-gradient-to-br from-emerald-50 via-white to-slate-50 p-4 shadow-sm" aria-label="CEDA lifecycle"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-black uppercase tracking-[0.16em] text-emerald-800">CEDA lifecycle</h2><p className="mt-1 text-sm text-slate-600">Capture → decision → learning is inspectable here. Review & Save remains the only approval workflow.</p></div><span className="rounded-full border border-emerald-200 bg-white px-3 py-1 text-xs font-bold text-emerald-800">Raw noise discarded</span></div><div className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-9">{stages.map(([label,detail],index)=><article key={label} className="relative rounded-2xl border border-white bg-white/85 p-3 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[0.12em] text-slate-400">{String(index+1).padStart(2,'0')}</p><h3 className="mt-1 text-sm font-black text-slate-950">{label}</h3><p className="mt-1 text-xs text-slate-500">{detail}</p></article>)}</div></section>}

function ReviewTable({items,selected,setSelected,onTransition,onEdit,onReminder}:{items:Item[];selected:Set<string>;setSelected:(value:Set<string>)=>void;onTransition:(item:Item,target:'approve'|'deny'|'delete'|'archive')=>void;onEdit:(item:Item)=>void;onReminder:(item:Item)=>void}){return <div className="overflow-x-auto"><table className="min-w-[980px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[0.12em] text-slate-500"><tr>{['','Type','Summary','Date','Area','Confidence','Status','Actions'].map(label=><th key={label} className="px-4 py-3 font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{items.map(item=><ReviewRow key={item.id} item={item} selected={selected.has(item.id)} onSelect={checked=>{const next=new Set(selected);if(checked)next.add(item.id);else next.delete(item.id);setSelected(next)}} onTransition={onTransition} onEdit={onEdit} onReminder={onReminder}/>) }{!items.length?<tr><td colSpan={8} className="p-12 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><CheckCircle2 size={26}/></div><h3 className="mt-3 text-base font-semibold text-slate-950">Nothing to review.</h3><p className="mt-1 text-sm text-slate-500">Kamal will surface new items as you work.</p></td></tr>:null}</tbody></table></div>}
function ReviewRow({item,selected,onSelect,onTransition,onEdit,onReminder}:{item:Item;selected:boolean;onSelect:(checked:boolean)=>void;onTransition:(item:Item,target:'approve'|'deny'|'delete'|'archive')=>void;onEdit:(item:Item)=>void;onReminder:(item:Item)=>void}){const sensitive=isSensitive(item);return <tr className="align-top hover:bg-slate-50/70"><td className="px-4 py-4"><input type="checkbox" checked={selected} onChange={event=>onSelect(event.target.checked)} className="h-4 w-4 accent-emerald-600"/></td><td className="px-4 py-4"><p className="font-semibold text-slate-950">{titleCase(item.type)}</p><div className="mt-2 flex flex-wrap gap-1.5"><SourceBadge value={item.source_type}/>{sensitive?<span className="rounded-full bg-rose-50 px-2 py-1 text-[10px] font-black uppercase text-rose-700">🔒 Sensitive</span>:null}</div></td><td className="max-w-md px-4 py-4"><SensitiveValue value={item.summary} sensitive={sensitive}/><p className="mt-2 text-xs leading-5 text-slate-500">{item.source_reference||'No raw source stored'} · v{item.version}</p></td><td className="px-4 py-4 text-slate-600">{item.key_date||new Date(item.created_at).toLocaleDateString()}</td><td className="px-4 py-4"><CategoryBadge value={item.related_area||item.domain}/></td><td className="px-4 py-4 font-semibold text-slate-700">{Math.round(item.confidence*100)}%</td><td className="px-4 py-4"><StatusBadge value={item.status}/></td><td className="px-4 py-4"><div className="flex flex-wrap gap-1.5">{item.status==='pending_review'?<><IconAction label="Approve" icon={<CheckCircle2 size={14}/>} onClick={()=>onTransition(item,'approve')} tone="emerald"/><IconAction label="Deny" icon={<XCircle size={14}/>} onClick={()=>onTransition(item,'deny')} tone="rose"/><IconAction label="Edit" icon={<Pencil size={14}/>} onClick={()=>onEdit(item)}/><IconAction label="Delete" icon={<Trash2 size={14}/>} onClick={()=>onTransition(item,'delete')} tone="rose"/></>:null}{item.status==='approved'&&item.key_date&&item.reminder_status!=='created'?<IconAction label="Create Reminder" icon={<CheckCircle2 size={14}/>} onClick={()=>onReminder(item)} tone="emerald"/>:null}<IconAction label="Archive" icon={<Trash2 size={14}/>} onClick={()=>onTransition(item,'archive')}/></div></td></tr>}
function SensitiveValue({value,sensitive}:{value:string;sensitive:boolean}){const [revealed,setRevealed]=useState(false);return <div className="flex items-start gap-2"><p className={`text-sm font-semibold leading-6 text-slate-950 ${sensitive&&!revealed?'select-none blur-[3px]':''}`}>{value}</p>{sensitive?<button type="button" title={revealed?'Hide sensitive value':'Reveal sensitive value'} aria-label={revealed?'Hide sensitive value':'Reveal sensitive value'} onClick={()=>setRevealed(v=>!v)} className="mt-0.5 rounded-full border border-rose-100 bg-rose-50 p-1.5 text-rose-700">{revealed?<EyeOff size={14}/>:<Eye size={14}/>}</button>:null}</div>}
function ReminderPlanner({reminders}:{reminders:Reminder[]}){const sorted=[...reminders].sort((a,b)=>(a.due_at||'9999').localeCompare(b.due_at||'9999'));const days=new Map<string,Reminder[]>();sorted.forEach(item=>{const key=item.due_at||'Unscheduled';days.set(key,[...(days.get(key)||[]),item])});return <div className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-semibold text-slate-900">Deadline Calendar</h3><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[...days].map(([day,entries])=><div key={day} className="min-h-24 rounded-xl border border-slate-200 p-3"><strong className="text-xs text-slate-800">{day}</strong>{entries.map(item=><p key={item.id} className="mt-2 text-[11px] leading-4 text-slate-600">{item.title}</p>)}</div>)}{!days.size?<p className="col-span-full text-sm text-slate-500">No reminders created yet.</p>:null}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-semibold text-slate-900">Upcoming by Priority</h3><div className="mt-3 space-y-2">{sorted.map(item=><div key={item.id} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-2"><strong className="text-sm text-slate-800">{item.title}</strong><StatusBadge value={item.priority}/></div><p className="mt-1 text-xs text-slate-500">Due {item.due_at||'not scheduled'} · remind {item.reminder_date||'policy controlled'}</p>{item.official_verification_required?<p className="mt-2 text-[10px] text-amber-700">Verify with your DSO, USCIS, or qualified counsel.</p>:null}</div>)}</div></section></div>}
function SourceTable({sources}:{sources:Source[]}){return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-[850px] w-full text-left text-xs"><thead className="bg-slate-50"><tr>{['Source Name','Source Type','Location','Category','Indexed','Last Updated','Policy','Status'].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{sources.map(item=><tr key={item.document_id} className="border-t border-slate-100"><td className="px-3 py-3 font-medium">{item.title}</td><td className="px-3 py-3">{item.source_kind}</td><td className="px-3 py-3">{item.physical_location}</td><td className="px-3 py-3">{item.domain}</td><td className="px-3 py-3">Yes</td><td className="px-3 py-3">{new Date(item.last_indexed_at).toLocaleString()}</td><td className="px-3 py-3">{item.policy_binding}</td><td className="px-3 py-3"><StatusBadge value={item.index_status}/></td></tr>)}</tbody></table></div>}
function HistoryTable({history}:{history:History[]}){return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-xs"><thead className="bg-slate-50"><tr>{['Time','Item','Action','Status Change','Actor','Notes'].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{history.map(item=><tr key={item.id} className="border-t border-slate-100"><td className="px-3 py-3">{new Date(item.timestamp).toLocaleString()}</td><td className="px-3 py-3">{item.item_id}</td><td className="px-3 py-3">{item.action}</td><td className="px-3 py-3">{item.old_status||'—'} → {item.new_status||'—'}</td><td className="px-3 py-3">{item.actor}</td><td className="px-3 py-3">{item.notes||'—'}</td></tr>)}</tbody></table></div>}
function CategoryBadge({value}:{value:string}){const normalized=value?.toLowerCase()||'personal';const tone=normalized.includes('academic')?'bg-blue-50 text-blue-800 border-blue-200':normalized.includes('immigration')?'bg-amber-50 text-amber-800 border-amber-200':normalized.includes('career')?'bg-violet-50 text-violet-800 border-violet-200':normalized.includes('health')?'bg-teal-50 text-teal-800 border-teal-200':normalized.includes('finance')?'bg-green-50 text-green-800 border-green-200':'bg-slate-50 text-slate-700 border-slate-200';return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-black uppercase ${tone}`}>{titleCase(value||'personal')}</span>}
function SourceBadge({value}:{value:string}){return <span className="inline-flex rounded-full border border-slate-200 bg-white px-2 py-1 text-[10px] font-semibold uppercase text-slate-500">{(value||'source').replaceAll('_',' ')}</span>}
function StatusBadge({value}:{value:string}){const normalized=value||'unknown';const tone=normalized==='pending_review'||normalized==='needs_review'?'bg-amber-50 text-amber-800 border-amber-200':normalized==='approved'||normalized==='saved'||normalized==='active'?'bg-emerald-50 text-emerald-800 border-emerald-200':normalized==='denied'||normalized==='rejected'?'bg-red-50 text-red-800 border-red-200':'bg-slate-100 text-slate-700 border-slate-200';return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-black uppercase ${tone}`}>{normalized.replaceAll('_',' ')}</span>}
function IconAction({label,icon,onClick,tone='slate'}:{label:string;icon:React.ReactNode;onClick:()=>void;tone?:'slate'|'emerald'|'rose'}){const classes=tone==='emerald'?'border-emerald-200 bg-emerald-50 text-emerald-800 hover:bg-emerald-100':tone==='rose'?'border-rose-200 bg-rose-50 text-rose-800 hover:bg-rose-100':'border-slate-200 bg-white text-slate-700 hover:bg-slate-50';return <button type="button" title={label} aria-label={label} onClick={onClick} className={`inline-flex h-8 min-w-8 items-center justify-center rounded-lg border px-2 text-xs font-bold ${classes}`}>{icon}<span className="sr-only">{label}</span></button>}
function isSensitive(item:Item){const haystack=`${item.type} ${item.domain} ${item.related_area} ${item.summary}`.toLowerCase();return Boolean(item.metadata?.sensitive)||/passport|visa|sevis|ssn|medical|health|financial|password|token|secret|credential/.test(haystack)}
function titleCase(value:string){return value.replace(/[-_]/g,' ').replace(/\b\w/g,letter=>letter.toUpperCase())}
